import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { discoverFpoFarmers } from "@/features/fpo/api/fpoFarmerApi";

export default function FpoFarmerDirectoryPage() {
  const [query, setQuery] = useState("");
  const result = useQuery({ queryKey: ["fpo-farmer-directory", query], queryFn: () => discoverFpoFarmers({ query, limit: 50 }) });
  const items = result.data?.items || [];
  return <div className="space-y-5"><div><h1 className="text-3xl font-black text-slate-950">Farmers</h1><p className="mt-1 text-sm text-slate-500">Farmers with an active or pending consent-backed relationship.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by farmer name or ID" className="w-full max-w-md rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-emerald-600" /></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-6 gap-4 border-b border-slate-100 px-5 py-3 text-xs font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Farmer</span><span>Village</span><span>District</span><span>Farms</span><span>Area</span><span>Status</span></div>{result.isLoading ? <p className="p-6 text-sm text-slate-500">Loading farmer directory…</p> : items.length ? items.map((item) => <div key={item.farmer_id} className="grid gap-2 border-b border-slate-100 px-5 py-4 text-sm md:grid-cols-6 md:items-center"><span className="font-bold text-slate-900">{item.farmer_name}<small className="block text-xs font-normal text-slate-400">{item.phone_masked || "Contact protected"}</small></span><span className="text-slate-600">{item.village_name || "—"}</span><span className="text-slate-600">{item.district_name || "—"}</span><span className="text-slate-600">{item.farm_count}</span><span className="text-slate-600">{Number(item.area_acres || 0).toFixed(2)} ac</span><span className="text-xs font-bold uppercase text-emerald-700">{String(item.relationship_status).replaceAll("_", " ")}</span></div>) : <p className="p-8 text-center text-sm text-slate-500">No farmers found.</p>}</div></div>;
}
