import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CalendarDays, ChevronRight, MapPin, TrendingDown, TrendingUp, X } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import LandGridMap from "@/components/ui-custom/LandGridMap";
import { CALCULATED_METRICS, interpretCalculatedMetric } from "@/features/land-intelligence/calculatedMetrics";
import { getFpoFarmIntelligence } from "../api/fpoFarmerApi";

const formatDate = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not available";
const locationOf = (farm) => [farm.village_name, farm.block_name, farm.district_name, farm.state_name].filter(Boolean).join(", ") || "Location not recorded";
const scoreOf = (row) => row?.score ?? row?.value ?? null;
const recommendationFor = (metric) => ({ water_stress: "Schedule an irrigation inspection for this farm.", heat_stress: "Check field moisture and heat exposure during the next field visit.", waterlogging_risk: "Inspect drainage and standing-water areas.", nutrient_stress_risk: "Arrange a field and soil review before applying inputs.", erosion_risk: "Inspect slopes, drainage paths, and exposed soil.", growth_anomaly: "Schedule a field inspection to confirm the growth change." }[metric] || "Review the crop condition during the next field visit.");

function StatusBadge({ interpretation }) { return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-bold ${interpretation.className}`}>{interpretation.label}</span>; }

function IntelligenceCard({ metric, row, onClick }) {
  const interpretation = interpretCalculatedMetric(metric.key, scoreOf(row));
  return <button type="button" onClick={onClick} className={`group rounded-2xl border p-5 text-left transition hover:-translate-y-0.5 hover:shadow-lg ${interpretation.surfaceClass}`}><div className="flex items-start justify-between gap-3"><p className="font-black text-slate-950">{metric.name}</p><ChevronRight className="h-4 w-4 text-slate-400 transition group-hover:translate-x-1" /></div><div className="mt-4 flex items-center gap-2"><StatusBadge interpretation={interpretation} />{scoreOf(row) !== null && <span className="text-lg font-black text-slate-950">· {Number(scoreOf(row)).toFixed(0)}</span>}</div><p className="mt-3 min-h-10 text-sm leading-5 text-slate-600">{interpretation.paragraph || interpretation.signalMeaning}</p><p className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-slate-500"><CalendarDays className="h-3.5 w-3.5" />Observed: {formatDate(row?.result_date)}</p></button>;
}

function HistoryModal({ metric, currentRow, history, onClose }) {
  const interpretation = interpretCalculatedMetric(metric.key, scoreOf(currentRow));
  const points = useMemo(() => history.filter((row) => row.prediction_key === metric.key && scoreOf(row) !== null).sort((a, b) => new Date(a.result_date) - new Date(b.result_date)), [history, metric.key]);
  const max = Math.max(100, ...points.map((row) => Number(scoreOf(row))));
  const first = points[0] ? Number(scoreOf(points[0])) : null;
  const last = points.at(-1) ? Number(scoreOf(points.at(-1))) : null;
  const trend = first !== null && last !== null && last !== first ? last > first ? "Increasing" : "Decreasing" : "Stable";
  useEffect(() => { const onKey = (event) => event.key === "Escape" && onClose(); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Parameter history</p><h2 className="mt-2 text-2xl font-black text-slate-950">{metric.name}</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label="Close"><X className="h-5 w-5" /></button></div><div className={`mt-5 rounded-2xl border p-4 ${interpretation.surfaceClass}`}><div className="flex flex-wrap items-center gap-2"><StatusBadge interpretation={interpretation} />{scoreOf(currentRow) !== null && <span className="text-2xl font-black text-slate-950">{Number(scoreOf(currentRow)).toFixed(0)}</span>}</div><p className="mt-2 text-sm text-slate-700">{interpretation.paragraph || interpretation.signalMeaning}</p><p className="mt-2 text-xs font-semibold text-slate-500">Latest observation: {formatDate(currentRow?.result_date)}</p></div><div className="mt-6 flex items-center justify-between"><h3 className="font-black text-slate-950">Historical movement</h3>{points.length > 1 && <span className="flex items-center gap-1 text-xs font-bold text-slate-500">{trend === "Increasing" ? <TrendingUp className="h-4 w-4" /> : trend === "Decreasing" ? <TrendingDown className="h-4 w-4" /> : null}{trend}</span>}</div>{points.length < 2 ? <p className="mt-4 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Historical data is not available yet.</p> : <div className="mt-4 space-y-3">{points.slice().reverse().map((row) => <div key={`${row.result_date}-${row.prediction_key}`} className="flex items-center gap-3"><span className="w-24 shrink-0 text-xs font-semibold text-slate-500">{formatDate(row.result_date)}</span><div className="h-8 flex-1 overflow-hidden rounded-lg bg-slate-100"><div className="h-full rounded-lg" style={{ width: `${Math.max(3, (Number(scoreOf(row)) / max) * 100)}%`, backgroundColor: interpretCalculatedMetric(metric.key, scoreOf(row)).color }} /></div><span className="w-10 text-right text-sm font-black text-slate-800">{Number(scoreOf(row)).toFixed(0)}</span></div>)}</div>}</div></div>;
}

export default function FpoFarmIntelligencePage() {
  const { farmerId, farmId } = useParams();
  const [selectedMetric, setSelectedMetric] = useState(null);
  const [mapParameter, setMapParameter] = useState(CALCULATED_METRICS[0].key);
  const query = useQuery({ queryKey: ["fpo-farm-intelligence", farmerId, farmId], queryFn: () => getFpoFarmIntelligence(farmerId, farmId), enabled: Boolean(farmerId && farmId) });
  if (query.isLoading) return <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading farm intelligence...</div>;
  if (query.isError) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700">Farm intelligence is unavailable or this farm is outside the active consent scope.</div>;
  const payload = query.data || {}; const farm = payload.farm || {}; const data = payload.data || {};
  const calculations = data.calculations?.items || []; const history = data.calculation_history?.items || []; const latest = data.latest || {}; const summary = data.summary || {};
  const gridValues = data.grid_values?.items || []; const gridCalculations = data.grid_calculations?.items || [];
  const gridCells = gridValues.map((cell) => ({ ...cell, ...(gridCalculations.find((item) => String(item.grid_cell_id) === String(cell.grid_cell_id)) || {}) }));
  const byKey = new Map(calculations.map((row) => [row.prediction_key, row])); const cards = CALCULATED_METRICS.map((metric) => ({ metric, row: byKey.get(metric.key) })); const selected = selectedMetric ? cards.find((item) => item.metric.key === selectedMetric) : null;
  const concern = cards.find(({ metric, row }) => { const status = interpretCalculatedMetric(metric.key, scoreOf(row)).status; return metric.direction === "risk" ? ["attention", "high", "critical"].includes(status) : ["attention", "poor", "critical"].includes(status); });
  const latestDate = calculations.map((row) => row.result_date).filter(Boolean).sort().at(-1) || latest.snapshot_date || summary.latest_observation_date;
  const overall = farm.overall_status || (calculations.length ? "NORMAL" : "NO_DATA"); const overallStyle = overall === "CRITICAL" ? "border-rose-200 bg-rose-50 text-rose-700" : overall === "NEEDS_ATTENTION" ? "border-orange-200 bg-orange-50 text-orange-700" : overall === "NO_DATA" ? "border-slate-200 bg-slate-100 text-slate-600" : "border-emerald-200 bg-emerald-50 text-emerald-700";
  return <div className="space-y-6 pb-10"><div><Link to="/fpo/monitoring" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700 hover:text-emerald-900"><ArrowLeft className="h-4 w-4" />Back to monitoring</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.16em] text-slate-400">Monitoring / {farm.farm_name || "Farm"}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black text-slate-950">{farm.farm_name || "Farm intelligence"}</h1><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${overallStyle}`}>{overall.replaceAll("_", " ")}</span></div><p className="mt-2 flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="h-4 w-4" />{locationOf(farm)}</p></div>
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-xs font-bold uppercase text-slate-400">Farmer</p><p className="mt-1 font-bold text-slate-900">{farm.farmer_name || "Farmer"}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Crop</p><p className="mt-1 font-bold text-slate-900">{farm.crop_name || "Not recorded"}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Crop stage</p><p className="mt-1 font-bold text-slate-900">{farm.crop_stage || "Not recorded"}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Area</p><p className="mt-1 font-bold text-slate-900">{farm.area_acres ? `${farm.area_acres} ac` : "Not recorded"}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Latest observation</p><p className="mt-1 font-bold text-slate-900">{formatDate(latestDate)}</p></div></section>
    <section><div className="mb-3"><h2 className="text-xl font-black text-slate-950">Farm intelligence</h2><p className="mt-1 text-sm text-slate-500">Select a parameter to review its historical movement.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(({ metric, row }) => <IntelligenceCard key={metric.key} metric={metric} row={row} onClick={() => setSelectedMetric(metric.key)} />)}</div></section>
    {concern && <section className="rounded-2xl border border-orange-200 bg-orange-50 p-5"><p className="text-xs font-black uppercase tracking-wide text-orange-700">Priority issue</p><p className="mt-1 text-lg font-black text-slate-950">{concern.metric.name}</p><p className="mt-1 text-sm text-slate-700">Suggested action: {recommendationFor(concern.metric.key)}</p></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-950">Farm map</h2><p className="mt-1 text-sm text-slate-500">Boundary and selected intelligence parameter. Grey areas indicate no data.</p></div><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><select value={mapParameter} onChange={(event) => setMapParameter(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{CALCULATED_METRICS.map((metric) => <option key={metric.key} value={metric.key}>{metric.name}</option>)}</select></label></div><div className="mt-4"><LandGridMap farm={farm} gridCells={gridCells} selectedParameter={mapParameter} /></div></section>
    {selected && <HistoryModal metric={selected.metric} currentRow={selected.row} history={history} onClose={() => setSelectedMetric(null)} />}</div>;
}
