BEGIN;

-- Multi-source environmental observation tables for MaatiTrace.
-- Sentinel-2 is intentionally NOT changed by this migration.
-- All tables reference canonical farms/farmer_profiles/fpos.

CREATE TABLE IF NOT EXISTS public.h3_sentinel1_features (
    feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    snapshot_date date NOT NULL,
    scene_id text NOT NULL,
    scene_datetime timestamptz,
    h3_resolution integer NOT NULL,
    h3_index bigint NOT NULL,
    mean_vv double precision,
    mean_vh double precision,
    mean_vv_db double precision,
    mean_vh_db double precision,
    vh_vv_ratio double precision,
    rvi double precision,
    observed_area_m2 double precision,
    valid_area_m2 double precision,
    invalid_area_m2 double precision,
    valid_fraction double precision,
    orbit_direction text,
    relative_orbit integer,
    native_resolution_m double precision,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_sentinel1_feature UNIQUE
        (farm_id, snapshot_date, scene_id, h3_index, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_sentinel1_farm_date
    ON public.h3_sentinel1_features(farm_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_h3_sentinel1_h3_date
    ON public.h3_sentinel1_features(h3_index, snapshot_date DESC);

CREATE TABLE IF NOT EXISTS public.h3_landsat_features (
    feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    snapshot_date date NOT NULL,
    scene_id text NOT NULL,
    scene_datetime timestamptz,
    scene_cloud_cover double precision,
    platform text,
    sensor text,
    h3_resolution integer NOT NULL,
    h3_index bigint NOT NULL,
    mean_blue double precision,
    mean_green double precision,
    mean_red double precision,
    mean_nir double precision,
    mean_swir16 double precision,
    mean_swir22 double precision,
    ndvi double precision,
    ndmi double precision,
    msi double precision,
    bsi double precision,
    nbr double precision,
    surface_temp_k double precision,
    surface_temp_c double precision,
    observed_area_m2 double precision,
    valid_area_m2 double precision,
    invalid_area_m2 double precision,
    valid_fraction double precision,
    optical_resolution_m integer,
    thermal_resolution_m integer,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_landsat_feature UNIQUE
        (farm_id, snapshot_date, scene_id, h3_index, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_landsat_farm_date
    ON public.h3_landsat_features(farm_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_h3_landsat_h3_date
    ON public.h3_landsat_features(h3_index, snapshot_date DESC);

CREATE TABLE IF NOT EXISTS public.farm_weather_observations (
    weather_observation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    observation_date date NOT NULL,
    precipitation_mm double precision,
    source_unit text,
    source_resolution_m double precision,
    aggregation_method text,
    source_dataset text NOT NULL,
    source_product_version text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_item_ids text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_weather_observation UNIQUE
        (farm_id, observation_date, source_dataset, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_weather_farm_date
    ON public.farm_weather_observations(farm_id, observation_date DESC);

CREATE TABLE IF NOT EXISTS public.h3_terrain_features (
    terrain_feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    h3_index bigint NOT NULL,
    h3_resolution integer NOT NULL,
    mean_elevation_m double precision,
    min_elevation_m double precision,
    max_elevation_m double precision,
    mean_slope_deg double precision,
    max_slope_deg double precision,
    mean_aspect_deg double precision,
    observed_area_m2 double precision,
    valid_area_m2 double precision,
    valid_fraction double precision,
    source_dataset text NOT NULL,
    source_version text,
    native_resolution_m double precision,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_terrain_feature UNIQUE
        (farm_id, h3_index, source_dataset, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_terrain_farm ON public.h3_terrain_features(farm_id);

CREATE TABLE IF NOT EXISTS public.h3_landcover_features (
    landcover_feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    h3_index bigint NOT NULL,
    h3_resolution integer NOT NULL,
    reference_year integer,
    dominant_class integer,
    dominant_fraction double precision,
    tree_cover_fraction double precision,
    shrubland_fraction double precision,
    grassland_fraction double precision,
    cropland_fraction double precision,
    built_fraction double precision,
    bare_sparse_fraction double precision,
    snow_ice_fraction double precision,
    permanent_water_fraction double precision,
    herbaceous_wetland_fraction double precision,
    mangrove_fraction double precision,
    moss_lichen_fraction double precision,
    observed_area_m2 double precision,
    valid_area_m2 double precision,
    valid_fraction double precision,
    source_dataset text NOT NULL,
    source_version text,
    native_resolution_m double precision,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_landcover_feature UNIQUE
        (farm_id, h3_index, reference_year, source_dataset, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_landcover_farm ON public.h3_landcover_features(farm_id);

CREATE TABLE IF NOT EXISTS public.h3_surface_water_features (
    surface_water_feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    h3_index bigint NOT NULL,
    h3_resolution integer NOT NULL,
    water_occurrence_pct double precision,
    water_recurrence_pct double precision,
    water_seasonality_months double precision,
    permanent_water_fraction double precision,
    historic_extent_fraction double precision,
    observed_area_m2 double precision,
    valid_area_m2 double precision,
    valid_fraction double precision,
    source_dataset text NOT NULL,
    source_reference_period text,
    native_resolution_m double precision,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_surface_water_feature UNIQUE
        (farm_id, h3_index, source_dataset, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_surface_water_farm ON public.h3_surface_water_features(farm_id);

CREATE TABLE IF NOT EXISTS public.farm_reanalysis_daily (
    reanalysis_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    observation_date date NOT NULL,
    dataset_key text NOT NULL,
    temperature_mean_c double precision,
    temperature_min_c double precision,
    temperature_max_c double precision,
    dewpoint_mean_c double precision,
    skin_temperature_mean_c double precision,
    soil_water_0_7 double precision,
    soil_water_7_28 double precision,
    soil_water_28_100 double precision,
    soil_water_100_289 double precision,
    source_resolution_m double precision,
    aggregation_method text,
    source_version text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_reanalysis_daily UNIQUE
        (farm_id, observation_date, dataset_key, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_reanalysis_farm_date
    ON public.farm_reanalysis_daily(farm_id, observation_date DESC);

CREATE TABLE IF NOT EXISTS public.h3_soilgrids_features (
    soil_feature_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    h3_index bigint NOT NULL,
    h3_resolution integer NOT NULL,
    property_key text NOT NULL,
    depth_top_cm integer NOT NULL,
    depth_bottom_cm integer NOT NULL,
    quantile text NOT NULL DEFAULT 'Q0.5',
    value double precision,
    unit text,
    valid_fraction double precision,
    source_dataset text NOT NULL,
    source_version text,
    native_resolution_m double precision,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    source_assets_used text[] NOT NULL DEFAULT ARRAY[]::text[],
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_h3_soilgrids_feature UNIQUE
        (farm_id, h3_index, property_key, depth_top_cm, depth_bottom_cm, quantile, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_h3_soilgrids_farm_property
    ON public.h3_soilgrids_features(farm_id, property_key, depth_top_cm, depth_bottom_cm);

CREATE TABLE IF NOT EXISTS public.farm_smap_observations (
    smap_observation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    observed_at timestamptz NOT NULL,
    surface_soil_moisture double precision,
    root_zone_soil_moisture double precision,
    source_dataset text NOT NULL,
    source_version text NOT NULL,
    source_resolution_m double precision,
    aggregation_method text,
    source_granule_id text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_smap_observation UNIQUE
        (farm_id, observed_at, source_dataset, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_smap_farm_time
    ON public.farm_smap_observations(farm_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS public.farm_modis_et_observations (
    modis_et_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    period_start date NOT NULL,
    period_end date NOT NULL,
    et_mm double precision,
    pet_mm double precision,
    latent_heat_j_m2_day double precision,
    potential_latent_heat_j_m2_day double precision,
    valid_fraction double precision,
    source_product text NOT NULL,
    source_version text,
    native_resolution_m double precision,
    aggregation_method text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_modis_et UNIQUE
        (farm_id, period_start, source_product, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_modis_et_farm_period
    ON public.farm_modis_et_observations(farm_id, period_start DESC);

CREATE TABLE IF NOT EXISTS public.farm_modis_vegetation_observations (
    modis_vegetation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    period_start date NOT NULL,
    period_end date NOT NULL,
    lai double precision,
    fpar double precision,
    lai_stddev double precision,
    fpar_stddev double precision,
    valid_fraction double precision,
    source_product text NOT NULL,
    source_version text,
    native_resolution_m double precision,
    aggregation_method text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_modis_vegetation UNIQUE
        (farm_id, period_start, source_product, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_modis_vegetation_farm_period
    ON public.farm_modis_vegetation_observations(farm_id, period_start DESC);

CREATE TABLE IF NOT EXISTS public.farm_weather_forecasts (
    forecast_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id uuid NOT NULL REFERENCES public.farms(farm_id) ON DELETE CASCADE,
    farmer_id uuid NOT NULL REFERENCES public.farmer_profiles(farmer_id),
    fpo_id uuid REFERENCES public.fpos(fpo_id),
    state_name text NOT NULL,
    district_name text NOT NULL,
    district_code integer,
    block_name text,
    block_code integer,
    provider text NOT NULL,
    model text,
    issued_at timestamptz NOT NULL,
    valid_at timestamptz NOT NULL,
    temperature_2m_c double precision,
    relative_humidity_2m double precision,
    precipitation_mm double precision,
    wind_speed_10m double precision,
    wind_direction_10m double precision,
    shortwave_radiation double precision,
    et0_mm double precision,
    vapour_pressure_deficit double precision,
    source_resolution_m double precision,
    aggregation_method text,
    source_provider text NOT NULL,
    source_collection text,
    source_item_id text NOT NULL,
    source_datetime timestamptz,
    processing_version text NOT NULL,
    parquet_uri text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_farm_weather_forecast UNIQUE
        (farm_id, provider, issued_at, valid_at, processing_version)
);
CREATE INDEX IF NOT EXISTS idx_farm_weather_forecast_farm_valid
    ON public.farm_weather_forecasts(farm_id, valid_at);

COMMIT;
