import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import FpoFeatureGate from "../access/FpoFeatureGate";
import { acknowledgeFpoDashboardAlert, getFpoDashboardAlerts } from "../api/fpoDashboardApi";

export default function FpoAlertsPage() {
  const [status, setStatus] = useState("OPEN");
  const alerts = useQuery({ queryKey: ["fpo-alerts", status], queryFn: () => getFpoDashboardAlerts(status) });
  return <FpoFeatureGate feature="BASIC_ALERTS" fallback={<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Operational alerts are not enabled for this organization.</div>}>
    <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-slate-950">Alerts</h1><p className="mt-1 text-sm text-slate-500">Auditable operational events for your consent-backed portfolio.</p></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="OPEN">Open</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="RESOLVED">Resolved</option></select></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{alerts.isLoading ? <p className="text-sm text-slate-500">Loading alerts...</p> : alerts.isError ? <p className="text-sm text-rose-700">Unable to load alerts.</p> : alerts.data?.length ? <div className="space-y-3">{alerts.data.map((alert) => <article key={alert.alert_id} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${alert.severity === "CRITICAL" ? "bg-rose-100 text-rose-700" : alert.severity === "WARNING" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{alert.severity}</span><h2 className="font-bold text-slate-900">{alert.title}</h2></div><p className="mt-2 text-sm text-slate-600">{alert.message}</p><p className="mt-2 text-xs text-slate-400">{alert.source || "SYSTEM"} · {alert.created_at ? new Date(alert.created_at).toLocaleString() : "Date unavailable"}</p></div>{alert.status === "OPEN" ? <button type="button" className="rounded-lg px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-50" onClick={async () => { await acknowledgeFpoDashboardAlert(alert.alert_id); alerts.refetch(); }}>Acknowledge</button> : <span className="text-xs font-bold uppercase text-slate-400">{alert.status}</span>}</div></article>)}</div> : <p className="py-8 text-center text-sm text-slate-500">No {status.toLowerCase()} alerts.</p>}</section></div>
  </FpoFeatureGate>;
}
