import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, FileOutput, Sprout } from "lucide-react";
import FpoFeatureGate from "../access/FpoFeatureGate";
import { getFpoForecasts, getFpoInputPlans, getFpoReportCatalogue, getFpoReportJobs, runFpoForecast } from "../api/fpoPortalApi";

function Gate({ feature, title, children }) { return <FpoFeatureGate feature={feature} fallback={<div className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-sm text-amber-800">{title} is not enabled for this organization.</div>}>{children}</FpoFeatureGate>; }
export function FpoInputsPage() { const q=useQuery({queryKey:["fpo-input-plans"],queryFn:getFpoInputPlans}); return <Gate feature="INPUT_REQUIREMENT_PLANNING" title="Input planning"><div className="space-y-6"><Header icon={Sprout} title="Input demand planning" copy="Calculated demand is tied to season targets and shows its calculation basis."/><section className="space-y-3">{(q.data||[]).map(p=><article key={p.input_plan_id} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">{p.name}</h2><p className="mt-1 text-xs text-slate-500">{p.status} · {p.calculation_version} · {p.calculated_at ? new Date(p.calculated_at).toLocaleString() : "Not calculated"}</p></article>)}{!q.data?.length&&<Empty text="No input-demand plans yet. Create a season plan first."/>}</section></div></Gate>; }
export function FpoForecastsPage() { const qc=useQueryClient(); const q=useQuery({queryKey:["fpo-forecasts"],queryFn:getFpoForecasts}); const run=useMutation({mutationFn:()=>runFpoForecast({crop_code:"PORTFOLIO"}),onSuccess:()=>qc.invalidateQueries({queryKey:["fpo-forecasts"]})}); return <Gate feature="YIELD_FORECASTS_STANDARD" title="Yield forecasts"><div className="space-y-6"><Header icon={BarChart3} title="Standard yield forecasts" copy="Forecasts always show confidence, model version, data freshness and quality status."/><button onClick={()=>run.mutate()} className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white">Run standard forecast</button><section className="space-y-3">{(q.data||[]).map(f=><article key={f.yield_forecast_id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h2 className="font-black">{f.crop_code}</h2><span className="text-xs font-bold text-slate-500">{f.quality_status}</span></div><p className="mt-2 text-sm text-slate-600">{f.forecast_yield_value} {f.forecast_yield_unit} · confidence {f.confidence_score ?? "not available"}</p><p className="mt-1 text-xs text-slate-500">Model {f.model_key} {f.model_version}</p></article>)}{!q.data?.length&&<Empty text="No forecasts have been calculated."/>}</section></div></Gate>; }
export function FpoAdvancedReportsPage() { const catalogue=useQuery({queryKey:["fpo-report-catalogue"],queryFn:getFpoReportCatalogue}); const jobs=useQuery({queryKey:["fpo-report-jobs"],queryFn:getFpoReportJobs}); return <Gate feature="ADVANCED_REPORTS" title="Advanced reports"><div className="space-y-6"><Header icon={FileOutput} title="Governed reports" copy="Report jobs run asynchronously with expiry and audit metadata."/><section className="grid gap-3 md:grid-cols-2">{(catalogue.data||[]).map(r=><article key={r.report_type} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">{r.label}</h2><p className="mt-2 text-xs text-slate-500">Available formats: {r.formats.join(", ")}</p></article>)}</section><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-black">Job history</h2>{(jobs.data||[]).map(j=><p key={j.report_job_id} className="mt-3 text-sm text-slate-600">{j.report_type} · {j.format} · {j.status}</p>)}{!jobs.data?.length&&<p className="mt-3 text-sm text-slate-500">No report jobs yet.</p>}</section></div></Gate>; }
function Header({ icon: Icon, title, copy }) { const HeaderIcon = Icon; return <header><HeaderIcon className="h-6 w-6 text-emerald-700"/><h1 className="mt-3 text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-600">{copy}</p></header>; }
function Empty({ text }) { return <p className="rounded-2xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">{text}</p>; }
