import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Plus, Radio, ShieldAlert } from "lucide-react";
import { useState } from "react";
import FpoFeatureGate from "../access/FpoFeatureGate";
import { createFpoAlertRule, getFpoAlertMetrics, getFpoAlertRules, getFpoMonitoringSummary, publishFpoAlertRule } from "../api/fpoPortalApi";

export default function FpoClassBMonitoringPage() {
  const qc = useQueryClient();
  const summary = useQuery({ queryKey: ["fpo-monitoring-summary"], queryFn: getFpoMonitoringSummary });
  const metrics = useQuery({ queryKey: ["fpo-alert-metrics"], queryFn: getFpoAlertMetrics });
  const rules = useQuery({ queryKey: ["fpo-alert-rules"], queryFn: getFpoAlertRules });
  const [name, setName] = useState(""); const [metric, setMetric] = useState("");
  const create = useMutation({ mutationFn: () => createFpoAlertRule({ name, feature_metric: metric, scope_type: "PORTFOLIO", condition_configuration: { operator: "GREATER_THAN", value: 0 }, severity: "WARNING" }), onSuccess: () => { setName(""); qc.invalidateQueries({ queryKey: ["fpo-alert-rules"] }); } });
  const publish = useMutation({ mutationFn: publishFpoAlertRule, onSuccess: () => qc.invalidateQueries({ queryKey: ["fpo-alert-rules"] }) });
  return <FpoFeatureGate feature="PORTFOLIO_MONITORING_ADVANCED" fallback={<div className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-sm text-amber-800">Advanced monitoring is not enabled for this organization.</div>}><div className="space-y-6"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Class B · Monitoring</p><h1 className="mt-2 text-3xl font-black">Monitoring rules</h1><p className="mt-2 text-sm text-slate-600">Create rules from the governed metric registry. Arbitrary SQL and expressions are never accepted.</p></header><div className="grid gap-4 sm:grid-cols-3">{[["Open alerts", summary.data?.open_alerts || 0, ShieldAlert], ["Critical alerts", summary.data?.critical_alerts || 0, Radio], ["Active rules", summary.data?.active_rules || 0, Activity]].map(([label, value, Icon]) => { const MetricIcon = Icon; return <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><MetricIcon className="h-5 w-5 text-emerald-700" /><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>; })}</div><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap gap-3"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Rule name" className="rounded-xl border border-slate-300 px-3 py-2 text-sm" /><select value={metric} onChange={(e) => setMetric(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">Select governed metric</option>{(metrics.data || []).map((m) => <option key={m.metric_key} value={m.metric_key}>{m.display_name}</option>)}</select><button disabled={!name || !metric} onClick={() => create.mutate()} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white"><Plus className="h-4 w-4" />Save draft</button></div></section><section className="space-y-3">{(rules.data || []).map((rule) => <article key={rule.alert_rule_id} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="min-w-0 flex-1"><h2 className="font-black">{rule.name}</h2><p className="mt-1 text-xs text-slate-500">{rule.feature_metric} · {rule.scope_type} · {rule.status}</p></div>{rule.status === "DRAFT" && <button onClick={() => publish.mutate(rule.alert_rule_id)} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-black text-emerald-700">Publish</button>}</article>)}{!rules.data?.length && <p className="text-sm text-slate-500">No alert rules yet.</p>}</section></div></FpoFeatureGate>;
}
