import { useEffect, useState } from "react";
import { FileSignature, MapPinned, ShoppingCart, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getFpoContracts, getFpoDispatches, getFpoOrders } from "../api/fpoPortalApi";

function Group({ title, icon: Icon, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-emerald-700" /><div><h2 className="font-black text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">Commercial records are operational; legal signing and payment remain outside this release.</p></div></div><div className="mt-4">{children}</div></section>; }

function Rows({ rows, empty }) { return rows.length ? <div className="divide-y divide-slate-100">{rows.map((row) => <div key={row.contract_id || row.order_id || row.dispatch_id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-bold text-slate-900">{row.contract_code || row.order_code || row.dispatch_code}</p><p className="text-xs text-slate-500">{row.title || row.counterparty_name || row.order_code} · {row.status}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase text-slate-600">{row.status}</span></div>)}</div> : <p className="text-sm text-slate-500">{empty}</p>; }

export default function FpoClassCExecutionPage() { const [contracts, setContracts] = useState([]); const [orders, setOrders] = useState([]); const [dispatches, setDispatches] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function load() { setLoading(true); try { const [c, o, d] = await Promise.all([getFpoContracts(), getFpoOrders(), getFpoDispatches()]); setContracts(c); setOrders(o); setDispatches(d); setError(""); } catch (e) { setError(e?.message || "Commercial execution is not enabled for this FPO."); } finally { setLoading(false); } } useEffect(() => { load(); }, []); return <div className="mx-auto max-w-[1400px] space-y-6 p-4 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-emerald-600">Class C · Execution</p><h1 className="mt-1 text-2xl font-black text-slate-950">Contracts, orders and logistics</h1><p className="mt-1 text-sm text-slate-500">Track commercial execution with controlled stock and dispatch transitions.</p></div><Button variant="outline" onClick={load} disabled={loading} className="rounded-xl"><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Refresh</Button></div>{error ? <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div> : null}<div className="grid gap-5 xl:grid-cols-3"><Group title="Contracts" icon={FileSignature}><Rows rows={contracts} empty="No commercial contracts yet." /></Group><Group title="Orders" icon={ShoppingCart}><Rows rows={orders} empty="No orders yet." /></Group><Group title="Dispatches" icon={MapPinned}><Rows rows={dispatches} empty="No dispatches yet." /></Group></div></div>; }
