import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Plus, RefreshCw } from "lucide-react";
import FpoFeatureGate from "../access/FpoFeatureGate";
import { createFpoSegment, createFpoSeasonPlan, createFpoTask, evaluateFpoSegment, getFpoSegments, getFpoSeasonPlans, getFpoTasks, updateFpoTask } from "../api/fpoPortalApi";

function Shell({ feature, eyebrow, title, description, children }) { return <FpoFeatureGate feature={feature} fallback={<div className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-sm text-amber-800">This Class B capability is not enabled for the organization.</div>}><div className="space-y-6"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Class B · {eyebrow}</p><h1 className="mt-2 text-3xl font-black text-slate-950">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></header>{children}</div></FpoFeatureGate>; }

export function FpoSegmentsPage() { const qc=useQueryClient(); const q=useQuery({queryKey:["fpo-segments"],queryFn:getFpoSegments}); const [name,setName]=useState(""); const create=useMutation({mutationFn:()=>createFpoSegment({name,segment_type:"DYNAMIC",criteria:{}}),onSuccess:()=>{setName("");qc.invalidateQueries({queryKey:["fpo-segments"]})}}); const evaluate=useMutation({mutationFn:evaluateFpoSegment,onSuccess:()=>qc.invalidateQueries({queryKey:["fpo-segments"]})}); return <Shell feature="FARMER_SEGMENTATION" eyebrow="Portfolio organization" title="Farmer segments" description="Create reusable, governed cohorts from the consented portfolio. Segment evaluation only uses server-owned projections."><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex gap-3"><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Segment name" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button disabled={!name||create.isPending} onClick={()=>create.mutate()} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white"><Plus className="h-4 w-4"/>Create segment</button></div></section><section className="grid gap-4 md:grid-cols-2">{(q.data||[]).map((s)=><article key={s.segment_id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="font-black">{s.name}</h2><p className="mt-1 text-xs text-slate-500">{s.segment_type} · {s.member_count} members</p></div><button onClick={()=>evaluate.mutate(s.segment_id)} className="rounded-lg border border-slate-200 p-2 text-slate-600" title="Evaluate segment"><RefreshCw className="h-4 w-4"/></button></div><p className="mt-4 text-xs text-slate-500">Last evaluated: {s.last_evaluated_at ? new Date(s.last_evaluated_at).toLocaleString() : "Not evaluated"}</p></article>)}{!q.data?.length&&<p className="text-sm text-slate-500">No segments yet.</p>}</section></Shell>; }

export function FpoSeasonsPage() { const qc=useQueryClient(); const q=useQuery({queryKey:["fpo-seasons"],queryFn:getFpoSeasonPlans}); const [name,setName]=useState(""); const create=useMutation({mutationFn:()=>createFpoSeasonPlan({name,season_code:"KHARIF",season_year:new Date().getFullYear(),planning_start_date:new Date().toISOString().slice(0,10),season_start_date:new Date().toISOString().slice(0,10),season_end_date:`${new Date().getFullYear()}-12-31`}),onSuccess:()=>{setName("");qc.invalidateQueries({queryKey:["fpo-seasons"]})}}); return <Shell feature="SEASON_PLANNING" eyebrow="Planning" title="Season plans" description="Set targets and review allocation without mutating farmer crop cycles automatically."><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex gap-3"><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Season plan name" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button disabled={!name} onClick={()=>create.mutate()} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white"><Plus className="h-4 w-4"/>Create draft</button></div></section><section className="space-y-3">{(q.data||[]).map((plan)=><article key={plan.season_plan_id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><div><h2 className="font-black">{plan.name}</h2><p className="mt-1 text-xs text-slate-500">{plan.season_code} {plan.season_year} · {plan.status}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">Draft planning</span></div></article>)}{!q.data?.length&&<p className="text-sm text-slate-500">No season plans yet.</p>}</section></Shell>; }

export function FpoTasksPage() { const qc=useQueryClient(); const q=useQuery({queryKey:["fpo-tasks"],queryFn:getFpoTasks}); const [title,setTitle]=useState(""); const create=useMutation({mutationFn:()=>createFpoTask({title,task_type:"FOLLOW_UP",priority:"NORMAL"}),onSuccess:()=>{setTitle("");qc.invalidateQueries({queryKey:["fpo-tasks"]})}}); const complete=useMutation({mutationFn:(id)=>updateFpoTask(id,{status:"COMPLETED",content:"Completed from FPO owner workspace."}),onSuccess:()=>qc.invalidateQueries({queryKey:["fpo-tasks"]})}); return <Shell feature="FIELD_ACTIVITY_PLANNING" eyebrow="Field operations" title="Tasks and follow-ups" description="Keep field activity visible and actionable for the single FPO owner account. No team assignment assumptions are introduced."><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex gap-3"><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Follow-up title" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button disabled={!title} onClick={()=>create.mutate()} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white"><Plus className="h-4 w-4"/>Add task</button></div></section><section className="space-y-3">{(q.data||[]).map((task)=><article key={task.task_id} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="min-w-0 flex-1"><h2 className="font-black">{task.title}</h2><p className="mt-1 text-xs text-slate-500">{task.priority} · {task.status}</p></div>{task.status!="COMPLETED"&&<button onClick={()=>complete.mutate(task.task_id)} className="rounded-lg border border-emerald-200 p-2 text-emerald-700" title="Complete task"><CheckCircle2 className="h-4 w-4"/></button>}</article>)}{!q.data?.length&&<p className="text-sm text-slate-500">No tasks yet.</p>}</section></Shell>; }
