import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, BarChart3, Download, FileText, RefreshCw, TrendingUp } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import FpoFeatureGate from "../access/FpoFeatureGate";
import { getFpoFarmMonitoring } from "../api/fpoFarmerApi";
import { getFpoDashboardReport } from "../api/fpoDashboardApi";
import { CALCULATED_METRICS } from "@/features/land-intelligence/calculatedMetrics";

const STATUS = ["NORMAL", "WATCH", "NEEDS_ATTENTION", "CRITICAL", "NO_DATA"];
const statusLabel = (value) => String(value || "NO_DATA").replaceAll("_", " ");
const statusClass = { NORMAL: "bg-emerald-500", WATCH: "bg-lime-500", NEEDS_ATTENTION: "bg-orange-500", CRITICAL: "bg-rose-500", NO_DATA: "bg-slate-400" };
const dateText = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not available";

function Card({ label, value, sub }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p>{sub && <p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>; }
function Bar({ value, total, color = "bg-emerald-500" }) { return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${total ? Math.max(value ? 3 : 0, (value / total) * 100) : 0}%` }} /></div>; }

export default function FpoReportsPage() {
  const [crop, setCrop] = useState(""); const [location, setLocation] = useState(""); const [stage, setStage] = useState("");
  const farmsQuery = useQuery({ queryKey: ["fpo-report-farms"], queryFn: () => getFpoFarmMonitoring(), staleTime: 30000 });
  const dashboard = useQuery({ queryKey: ["fpo-report-dashboard"], queryFn: getFpoDashboardReport, staleTime: 30000 });
  const farms = farmsQuery.data?.items || [];
  const crops = [...new Set(farms.map((farm) => farm.crop_name || farm.crop_code).filter(Boolean))].sort();
  const locations = [...new Set(farms.map((farm) => farm.village_name || farm.block_name).filter(Boolean))].sort();
  const stages = [...new Set(farms.map((farm) => farm.crop_stage).filter(Boolean))].sort();
  const filtered = useMemo(() => farms.filter((farm) => (!crop || (farm.crop_name || farm.crop_code) === crop) && (!location || (farm.village_name || farm.block_name) === location) && (!stage || farm.crop_stage === stage)), [farms, crop, location, stage]);
  const summary = useMemo(() => {
    const counts = Object.fromEntries(STATUS.map((status) => [status, 0]));
    filtered.forEach((farm) => { counts[farm.overall_status || "NO_DATA"] = (counts[farm.overall_status || "NO_DATA"] || 0) + 1; });
    const parameterRows = CALCULATED_METRICS.map((metric) => { const values = filtered.map((farm) => (farm.predictions || []).find((item) => item.prediction_key === metric.key)).filter(Boolean); const states = Object.fromEntries(STATUS.map((status) => [status, 0])); values.forEach((item) => { const label = String(item.status_label || "NO_DATA").toUpperCase(); const state = label === "GOOD" ? "NORMAL" : label === "FAIR" ? "WATCH" : ["HIGH", "POOR", "ATTENTION"].includes(label) ? "NEEDS_ATTENTION" : label === "CRITICAL" ? "CRITICAL" : "NO_DATA"; states[state] += 1; }); const scores = values.map((item) => Number(item.score)).filter(Number.isFinite); return { ...metric, states, average: scores.length ? Math.round(scores.reduce((sum, value) => sum + value, 0) / scores.length) : null }; });
    const issueRows = parameterRows.map((row) => ({ ...row, affected: row.states.NEEDS_ATTENTION + row.states.CRITICAL })).sort((a, b) => b.affected - a.affected);
    return { counts, parameterRows, issueRows, alerts: filtered.reduce((sum, farm) => sum + Number(farm.open_alert_count || 0), 0), area: filtered.reduce((sum, farm) => sum + Number(farm.area_acres || 0), 0) };
  }, [filtered]);
  const dataThrough = dashboard.data?.data_freshness?.data_through || farms.map((farm) => farm.latest_observation_date || farm.latest_analysis_date).filter(Boolean).sort().at(-1);
  const download = () => { const header = ["Parameter", "Normal", "Watch", "Needs attention", "Critical", "Average score"]; const rows = summary.parameterRows.map((row) => [row.name, row.states.NORMAL, row.states.WATCH, row.states.NEEDS_ATTENTION, row.states.CRITICAL, row.average ?? ""]); const blob = new Blob([[header, ...rows].map((row) => row.join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "fpo-intelligence-report.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <FpoFeatureGate feature="BASIC_REPORTS" fallback={<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Portfolio reports are not enabled for this organization.</div>}><div className="space-y-6 pb-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">FPO reports</p><h1 className="mt-2 text-3xl font-black text-slate-950">Portfolio intelligence report</h1><p className="mt-1 text-sm text-slate-500">Aggregated farm, crop, location, alert, and intelligence trends.</p></div><button type="button" onClick={download} disabled={!filtered.length} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50"><Download className="h-4 w-4" />Export CSV</button></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center gap-3"><select value={crop} onChange={(event) => setCrop(event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All crops</option>{crops.map((item) => <option key={item}>{item}</option>)}</select><select value={stage} onChange={(event) => setStage(event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All crop stages</option>{stages.map((item) => <option key={item}>{item}</option>)}</select><select value={location} onChange={(event) => setLocation(event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All villages / blocks</option>{locations.map((item) => <option key={item}>{item}</option>)}</select><button type="button" onClick={() => { setCrop(""); setStage(""); setLocation(""); }} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-600">Clear filters</button><span className="ml-auto text-xs font-bold text-slate-400">{filtered.length} farms included · Data through {dateText(dataThrough)}</span></div></section>
    {farmsQuery.isLoading ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Preparing report...</div> : farmsQuery.isError ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700">Unable to load the report data.</div> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card label="Farms analyzed" value={filtered.length} /><Card label="Critical farms" value={summary.counts.CRITICAL} /><Card label="Needs attention" value={summary.counts.NEEDS_ATTENTION} /><Card label="Stale / no data" value={summary.counts.NO_DATA} /><Card label="Open alerts" value={summary.alerts} /><Card label="Area covered" value={`${summary.area.toFixed(1)} ac`} /></section>
      <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-emerald-700" /><h2 className="font-black text-slate-950">Farm status distribution</h2></div><div className="mt-5 space-y-4">{STATUS.map((status) => <div key={status}><div className="mb-1 flex justify-between text-sm"><span className="font-semibold text-slate-600">{statusLabel(status)}</span><span className="font-black text-slate-900">{summary.counts[status]}</span></div><Bar value={summary.counts[status]} total={filtered.length} color={statusClass[status]} /></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-orange-600" /><h2 className="font-black text-slate-950">Most common issues</h2></div><div className="mt-5 space-y-4">{summary.issueRows.slice(0, 5).map((row) => <div key={row.key}><div className="mb-1 flex justify-between text-sm"><span className="font-semibold text-slate-600">{row.name}</span><span className="font-black text-slate-900">{row.affected} farms</span></div><Bar value={row.affected} total={filtered.length} color="bg-orange-500" /></div>)}</div></article></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-slate-950">Ten-parameter performance</h2><p className="mt-1 text-sm text-slate-500">Aggregated intelligence by status; open a farm from Monitoring for detailed history.</p></div><Link to="/fpo/monitoring" className="text-sm font-bold text-emerald-700">Open monitoring →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-100 text-[10px] uppercase tracking-wide text-slate-400"><tr><th className="px-3 py-3">Parameter</th><th className="px-3 py-3">Normal</th><th className="px-3 py-3">Watch</th><th className="px-3 py-3">Needs attention</th><th className="px-3 py-3">Critical</th><th className="px-3 py-3">Average score</th></tr></thead><tbody>{summary.parameterRows.map((row) => <tr key={row.key} className="border-b border-slate-50"><td className="px-3 py-3 font-bold text-slate-900">{row.name}</td><td className="px-3 py-3 text-emerald-700">{row.states.NORMAL}</td><td className="px-3 py-3 text-lime-700">{row.states.WATCH}</td><td className="px-3 py-3 text-orange-700">{row.states.NEEDS_ATTENTION}</td><td className="px-3 py-3 text-rose-700">{row.states.CRITICAL}</td><td className="px-3 py-3 font-black">{row.average ?? "—"}</td></tr>)}</tbody></table></div></section>
      <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-emerald-700" /><h2 className="font-black text-slate-950">Operational interpretation</h2></div><p className="mt-4 text-sm leading-6 text-slate-600">{summary.counts.CRITICAL ? `${summary.counts.CRITICAL} farms are currently critical and should be prioritized for field follow-up.` : summary.counts.NEEDS_ATTENTION ? `${summary.counts.NEEDS_ATTENTION} farms need attention and should be reviewed by the field team.` : "No critical or attention-level farms are present in the selected report."}</p><p className="mt-3 text-sm leading-6 text-slate-600">{summary.issueRows[0]?.affected ? `${summary.issueRows[0].name} is the most common issue in the selected portfolio.` : "There is not enough calculated intelligence to identify a leading issue."}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-emerald-700" /><h2 className="font-black text-slate-950">Report scope</h2></div><p className="mt-4 text-sm leading-6 text-slate-600">This report aggregates the same consent-scoped farm intelligence used by Monitoring. It does not replace the individual farm page, which contains parameter history and the farm map.</p><p className="mt-3 text-xs text-slate-400">Last refresh: {dateText(dataThrough)} · <RefreshCw className="inline h-3 w-3" /> Read-only report</p></article></section></>}</div></FpoFeatureGate>;
}
