import { useEffect, useState } from "react";
import { Building2, MapPin, Users } from "lucide-react";
import { getFpoFarmers, getFpoFarms, getFpos } from "@/lib/api/fpo";

export default function AdminFpoRegistryPage() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([getFpos(),]).then(async ([fpos]) => setItems(await Promise.all((fpos || []).map(async (fpo) => ({ ...fpo, farmers: await getFpoFarmers(fpo.fpo_id).catch(() => []), farms: await getFpoFarms(fpo.fpo_id).catch(() => []) }))))) .finally(() => setLoading(false)); }, []);
  return <div className="mx-auto max-w-[1400px] space-y-6 p-4 md:p-6"><header><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Admin / Registry</p><h1 className="mt-1 text-3xl font-black text-slate-950">FPO Registry</h1><p className="mt-1 text-sm text-slate-500">Complete directory of registered Farmer Producer Organisations and their connected portfolio.</p></header><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-3 border-b border-slate-100 bg-slate-50 p-4 text-center"><div><p className="text-2xl font-black text-slate-900">{items.length}</p><p className="text-xs font-bold uppercase text-slate-400">FPOs</p></div><div><p className="text-2xl font-black text-slate-900">{items.reduce((s, x) => s + x.farmers.length, 0)}</p><p className="text-xs font-bold uppercase text-slate-400">Farmers</p></div><div><p className="text-2xl font-black text-slate-900">{items.reduce((s, x) => s + x.farms.length, 0)}</p><p className="text-xs font-bold uppercase text-slate-400">Farms</p></div></div><div className="divide-y divide-slate-100">{loading ? <p className="p-8 text-center text-sm text-slate-500">Loading FPO registry...</p> : items.map((fpo) => <article key={fpo.fpo_id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Building2 className="h-5 w-5" /></div><div><h2 className="font-bold text-slate-900">{fpo.fpo_name || "Unnamed FPO"}</h2><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-3 w-3" />{[fpo.district_name, fpo.state_name].filter(Boolean).join(", ") || "Location pending"}</p></div></div><div className="flex gap-5 text-right text-xs text-slate-500"><span><Users className="mx-auto mb-1 h-4 w-4 text-sky-500" />{fpo.farmers.length} farmers</span><span><Building2 className="mx-auto mb-1 h-4 w-4 text-emerald-500" />{fpo.farms.length} farms</span></div></article>)}{!loading && !items.length ? <p className="p-8 text-center text-sm text-slate-500">No FPO records found.</p> : null}</div></section></div>;
}
